// Generated by gencpp from file vehicle_msgs/PositionData.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_POSITIONDATA_H
#define VEHICLE_MSGS_MESSAGE_POSITIONDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_msgs
{
template <class ContainerAllocator>
struct PositionData_
{
  typedef PositionData_<ContainerAllocator> Type;

  PositionData_()
    : gps_flag(0)
    , gps_week(0)
    , gps_millisecond(0.0)
    , llhPos()
    , gaussPos()
    , height(0)
    , pitch(0)
    , roll(0)
    , azimuth(0)
    , northVelocity(0)
    , eastVelocity(0)
    , upVelocity(0)
    , positionStatus(0)
    , motion_flag(0)
    , motion_week(0)
    , motion_millisecond(0)
    , drPos()
    , drHeight(0)
    , drAzimuth(0)
    , drNorthVelocity(0)
    , drEastVelocity(0)
    , drUpVelocity(0)
    , reserved()  {
      llhPos.assign(0);

      gaussPos.assign(0);

      drPos.assign(0);

      reserved.assign(0);
  }
  PositionData_(const ContainerAllocator& _alloc)
    : gps_flag(0)
    , gps_week(0)
    , gps_millisecond(0.0)
    , llhPos()
    , gaussPos()
    , height(0)
    , pitch(0)
    , roll(0)
    , azimuth(0)
    , northVelocity(0)
    , eastVelocity(0)
    , upVelocity(0)
    , positionStatus(0)
    , motion_flag(0)
    , motion_week(0)
    , motion_millisecond(0)
    , drPos()
    , drHeight(0)
    , drAzimuth(0)
    , drNorthVelocity(0)
    , drEastVelocity(0)
    , drUpVelocity(0)
    , reserved()  {
  (void)_alloc;
      llhPos.assign(0);

      gaussPos.assign(0);

      drPos.assign(0);

      reserved.assign(0);
  }



   typedef int16_t _gps_flag_type;
  _gps_flag_type gps_flag;

   typedef int16_t _gps_week_type;
  _gps_week_type gps_week;

   typedef double _gps_millisecond_type;
  _gps_millisecond_type gps_millisecond;

   typedef boost::array<int32_t, 2>  _llhPos_type;
  _llhPos_type llhPos;

   typedef boost::array<int32_t, 2>  _gaussPos_type;
  _gaussPos_type gaussPos;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _pitch_type;
  _pitch_type pitch;

   typedef int32_t _roll_type;
  _roll_type roll;

   typedef int32_t _azimuth_type;
  _azimuth_type azimuth;

   typedef int32_t _northVelocity_type;
  _northVelocity_type northVelocity;

   typedef int32_t _eastVelocity_type;
  _eastVelocity_type eastVelocity;

   typedef int32_t _upVelocity_type;
  _upVelocity_type upVelocity;

   typedef int32_t _positionStatus_type;
  _positionStatus_type positionStatus;

   typedef int16_t _motion_flag_type;
  _motion_flag_type motion_flag;

   typedef int16_t _motion_week_type;
  _motion_week_type motion_week;

   typedef int32_t _motion_millisecond_type;
  _motion_millisecond_type motion_millisecond;

   typedef boost::array<int32_t, 2>  _drPos_type;
  _drPos_type drPos;

   typedef int32_t _drHeight_type;
  _drHeight_type drHeight;

   typedef int32_t _drAzimuth_type;
  _drAzimuth_type drAzimuth;

   typedef int32_t _drNorthVelocity_type;
  _drNorthVelocity_type drNorthVelocity;

   typedef int32_t _drEastVelocity_type;
  _drEastVelocity_type drEastVelocity;

   typedef int32_t _drUpVelocity_type;
  _drUpVelocity_type drUpVelocity;

   typedef boost::array<int32_t, 2>  _reserved_type;
  _reserved_type reserved;





  typedef boost::shared_ptr< ::vehicle_msgs::PositionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::PositionData_<ContainerAllocator> const> ConstPtr;

}; // struct PositionData_

typedef ::vehicle_msgs::PositionData_<std::allocator<void> > PositionData;

typedef boost::shared_ptr< ::vehicle_msgs::PositionData > PositionDataPtr;
typedef boost::shared_ptr< ::vehicle_msgs::PositionData const> PositionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::PositionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::PositionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vehicle_msgs': ['/home/ubuntu/AutoAx7/ShuaiKe_Sensor/ros_cam/src/vehicle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::PositionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::PositionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::PositionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::PositionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::PositionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::PositionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::PositionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe95a850af88fa96dc6d597d5f291e37";
  }

  static const char* value(const ::vehicle_msgs::PositionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe95a850af88fa96ULL;
  static const uint64_t static_value2 = 0xdc6d597d5f291e37ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::PositionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/PositionData";
  }

  static const char* value(const ::vehicle_msgs::PositionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::PositionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 gps_flag       #gps info is updated\n\
int16 gps_week\n\
float64 gps_millisecond        #millisecond in a week\n\
int32[2] llhPos	#经纬度，llpos[i]/SC_POS 单位为度\n\
int32[2] gaussPos  #高斯投影位置,cm，\n\
int32 height         #cm\n\
int32 pitch  #欧拉角，单位为0.01度\n\
int32 roll   #欧拉角，单位为0.01度\n\
int32 azimuth        #欧拉角，单位为0.01度,向东为零度，逆时针0-360\n\
int32 northVelocity  #north速度，单位为cm/s\n\
int32 eastVelocity\n\
int32 upVelocity\n\
int32 positionStatus	  	#系统运行状态\n\
int16 motion_flag    # motion info is updated\n\
int16 motion_week\n\
int32 motion_millisecond\n\
int32[2] drPos\n\
int32 drHeight\n\
int32 drAzimuth\n\
int32 drNorthVelocity\n\
int32 drEastVelocity\n\
int32 drUpVelocity\n\
int32[2] reserved\n\
\n\
";
  }

  static const char* value(const ::vehicle_msgs::PositionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::PositionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gps_flag);
      stream.next(m.gps_week);
      stream.next(m.gps_millisecond);
      stream.next(m.llhPos);
      stream.next(m.gaussPos);
      stream.next(m.height);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.azimuth);
      stream.next(m.northVelocity);
      stream.next(m.eastVelocity);
      stream.next(m.upVelocity);
      stream.next(m.positionStatus);
      stream.next(m.motion_flag);
      stream.next(m.motion_week);
      stream.next(m.motion_millisecond);
      stream.next(m.drPos);
      stream.next(m.drHeight);
      stream.next(m.drAzimuth);
      stream.next(m.drNorthVelocity);
      stream.next(m.drEastVelocity);
      stream.next(m.drUpVelocity);
      stream.next(m.reserved);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::PositionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::PositionData_<ContainerAllocator>& v)
  {
    s << indent << "gps_flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gps_flag);
    s << indent << "gps_week: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gps_week);
    s << indent << "gps_millisecond: ";
    Printer<double>::stream(s, indent + "  ", v.gps_millisecond);
    s << indent << "llhPos[]" << std::endl;
    for (size_t i = 0; i < v.llhPos.size(); ++i)
    {
      s << indent << "  llhPos[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.llhPos[i]);
    }
    s << indent << "gaussPos[]" << std::endl;
    for (size_t i = 0; i < v.gaussPos.size(); ++i)
    {
      s << indent << "  gaussPos[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.gaussPos[i]);
    }
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "pitch: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<int32_t>::stream(s, indent + "  ", v.roll);
    s << indent << "azimuth: ";
    Printer<int32_t>::stream(s, indent + "  ", v.azimuth);
    s << indent << "northVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.northVelocity);
    s << indent << "eastVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.eastVelocity);
    s << indent << "upVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.upVelocity);
    s << indent << "positionStatus: ";
    Printer<int32_t>::stream(s, indent + "  ", v.positionStatus);
    s << indent << "motion_flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motion_flag);
    s << indent << "motion_week: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motion_week);
    s << indent << "motion_millisecond: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motion_millisecond);
    s << indent << "drPos[]" << std::endl;
    for (size_t i = 0; i < v.drPos.size(); ++i)
    {
      s << indent << "  drPos[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.drPos[i]);
    }
    s << indent << "drHeight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drHeight);
    s << indent << "drAzimuth: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drAzimuth);
    s << indent << "drNorthVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drNorthVelocity);
    s << indent << "drEastVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drEastVelocity);
    s << indent << "drUpVelocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drUpVelocity);
    s << indent << "reserved[]" << std::endl;
    for (size_t i = 0; i < v.reserved.size(); ++i)
    {
      s << indent << "  reserved[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.reserved[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_POSITIONDATA_H
