// Generated by gencpp from file vehiclemap_msg/NEGATIVE_OBSTACLE_OBJ.msg
// DO NOT EDIT!


#ifndef VEHICLEMAP_MSG_MESSAGE_NEGATIVE_OBSTACLE_OBJ_H
#define VEHICLEMAP_MSG_MESSAGE_NEGATIVE_OBSTACLE_OBJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehiclemap_msg
{
template <class ContainerAllocator>
struct NEGATIVE_OBSTACLE_OBJ_
{
  typedef NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> Type;

  NEGATIVE_OBSTACLE_OBJ_()
    : NegObID(0)
    , CenterX(0)
    , CenterY(0)
    , AxisX(0)
    , AxisY(0)
    , Slope(0)  {
    }
  NEGATIVE_OBSTACLE_OBJ_(const ContainerAllocator& _alloc)
    : NegObID(0)
    , CenterX(0)
    , CenterY(0)
    , AxisX(0)
    , AxisY(0)
    , Slope(0)  {
  (void)_alloc;
    }



   typedef int32_t _NegObID_type;
  _NegObID_type NegObID;

   typedef int32_t _CenterX_type;
  _CenterX_type CenterX;

   typedef int32_t _CenterY_type;
  _CenterY_type CenterY;

   typedef int32_t _AxisX_type;
  _AxisX_type AxisX;

   typedef int32_t _AxisY_type;
  _AxisY_type AxisY;

   typedef int32_t _Slope_type;
  _Slope_type Slope;




  typedef boost::shared_ptr< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> const> ConstPtr;

}; // struct NEGATIVE_OBSTACLE_OBJ_

typedef ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<std::allocator<void> > NEGATIVE_OBSTACLE_OBJ;

typedef boost::shared_ptr< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ > NEGATIVE_OBSTACLE_OBJPtr;
typedef boost::shared_ptr< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ const> NEGATIVE_OBSTACLE_OBJConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehiclemap_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'vehiclemap_msg': ['/home/jbh/catkin_ws/src/vehiclemap_msg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea31db64d0c73cb8bc9813012d7fbcf6";
  }

  static const char* value(const ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea31db64d0c73cb8ULL;
  static const uint64_t static_value2 = 0xbc9813012d7fbcf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehiclemap_msg/NEGATIVE_OBSTACLE_OBJ";
  }

  static const char* value(const ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 NegObID\n\
int32 CenterX    #cm为单位，惯导坐标系\n\
int32 CenterY\n\
int32 AxisX      #长轴，cm为单位\n\
int32 AxisY      #短轴，cm为单位\n\
int32 Slope      # 斜率，0.01度，逆时针为正\n\
";
  }

  static const char* value(const ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.NegObID);
      stream.next(m.CenterX);
      stream.next(m.CenterY);
      stream.next(m.AxisX);
      stream.next(m.AxisY);
      stream.next(m.Slope);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NEGATIVE_OBSTACLE_OBJ_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehiclemap_msg::NEGATIVE_OBSTACLE_OBJ_<ContainerAllocator>& v)
  {
    s << indent << "NegObID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.NegObID);
    s << indent << "CenterX: ";
    Printer<int32_t>::stream(s, indent + "  ", v.CenterX);
    s << indent << "CenterY: ";
    Printer<int32_t>::stream(s, indent + "  ", v.CenterY);
    s << indent << "AxisX: ";
    Printer<int32_t>::stream(s, indent + "  ", v.AxisX);
    s << indent << "AxisY: ";
    Printer<int32_t>::stream(s, indent + "  ", v.AxisY);
    s << indent << "Slope: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Slope);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLEMAP_MSG_MESSAGE_NEGATIVE_OBSTACLE_OBJ_H
