// Generated by gencpp from file vehiclemap_msg/TRAFFIC_LIGHT.msg
// DO NOT EDIT!


#ifndef VEHICLEMAP_MSG_MESSAGE_TRAFFIC_LIGHT_H
#define VEHICLEMAP_MSG_MESSAGE_TRAFFIC_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehiclemap_msg
{
template <class ContainerAllocator>
struct TRAFFIC_LIGHT_
{
  typedef TRAFFIC_LIGHT_<ContainerAllocator> Type;

  TRAFFIC_LIGHT_()
    : pos_flag(0)
    , x(0)
    , y(0)
    , forward_light_type(0)
    , left_light_type(0)
    , right_light_type(0)
    , uturn_light_type(0)  {
    }
  TRAFFIC_LIGHT_(const ContainerAllocator& _alloc)
    : pos_flag(0)
    , x(0)
    , y(0)
    , forward_light_type(0)
    , left_light_type(0)
    , right_light_type(0)
    , uturn_light_type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _pos_flag_type;
  _pos_flag_type pos_flag;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef uint8_t _forward_light_type_type;
  _forward_light_type_type forward_light_type;

   typedef uint8_t _left_light_type_type;
  _left_light_type_type left_light_type;

   typedef uint8_t _right_light_type_type;
  _right_light_type_type right_light_type;

   typedef uint8_t _uturn_light_type_type;
  _uturn_light_type_type uturn_light_type;




  typedef boost::shared_ptr< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> const> ConstPtr;

}; // struct TRAFFIC_LIGHT_

typedef ::vehiclemap_msg::TRAFFIC_LIGHT_<std::allocator<void> > TRAFFIC_LIGHT;

typedef boost::shared_ptr< ::vehiclemap_msg::TRAFFIC_LIGHT > TRAFFIC_LIGHTPtr;
typedef boost::shared_ptr< ::vehiclemap_msg::TRAFFIC_LIGHT const> TRAFFIC_LIGHTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehiclemap_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'vehiclemap_msg': ['/home/jbh/catkin_ws/src/vehiclemap_msg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3902b131172341878751daf0048c8941";
  }

  static const char* value(const ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3902b13117234187ULL;
  static const uint64_t static_value2 = 0x8751daf0048c8941ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehiclemap_msg/TRAFFIC_LIGHT";
  }

  static const char* value(const ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 pos_flag		 #是否有效\n\
int32 x			 #坐标\n\
int32 y\n\
uint8 forward_light_type  #/*直行灯信息*/\n\
uint8 left_light_type     #/*左转灯信息*/\n\
uint8 right_light_type    #/*右转灯信息*/\n\
uint8 uturn_light_type    #/*U Turn灯信息*/\n\
";
  }

  static const char* value(const ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_flag);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.forward_light_type);
      stream.next(m.left_light_type);
      stream.next(m.right_light_type);
      stream.next(m.uturn_light_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TRAFFIC_LIGHT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehiclemap_msg::TRAFFIC_LIGHT_<ContainerAllocator>& v)
  {
    s << indent << "pos_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos_flag);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "forward_light_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward_light_type);
    s << indent << "left_light_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_light_type);
    s << indent << "right_light_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_light_type);
    s << indent << "uturn_light_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.uturn_light_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLEMAP_MSG_MESSAGE_TRAFFIC_LIGHT_H
