Header  header
int32 	messageID              #为每一个MSG设定唯一的标识码

FrameStamp localStamp
FrameStamp globalStamp
 
int32 camera_obstacle_id
float64 camera_obstacleposx
float64 camera_obstacleposy
int32 blinkerInfo
int32 cut_in_and_out
int32 obstacle_type
int32 obstacle_status
int32 obstacle_valid
int32 obstacles_brake_lights
float64 obstacle_length
float64 obstacle_width
float64 obstacles_velx

int32 obstacleAge
int32 obstacleLane
int32 CIPVFlag
float64 RadarPosX
float64 RadarVelX
int32 RadarMatchConfidence
int32 MatcheRadarID

float64 obstacleAngleRate
int32 obstacles_velY
float64 object_Accel_X
int32 obstacleReplaced
float64 obstacleAngle
