#  ID=0x303, Len=4, 100ms
uint8  FrontWiperCtrlCmd     #  前雨刮控制命令
uint8  RearWiperCtrlCmd      #  后雨刮控制命令
uint8  LowBeamCtrlCmd        #  近光灯控制命令
uint8  HighBeamCtrlCmd       #  远光灯控制命令
uint8  BackFogLightCtrlCmd   #  后雾灯控制命令
uint8  FrontFogLightCtrlCmd  #  前雾灯控制命令
uint8  PositionLampCtrlCmd   #  位置灯控制命令
uint8  LeftLightCtrlCmd      #  左转向控制命令
uint8  RightLightCtrlCmd     #  右转向控制命令
uint8  HarzadCtrlCmd         #  危险报警灯控制命令
uint8  BrakeLampCtrlCmd      #  刹车灯控制命令
uint8  ReversingLampCtrlCmd  #  倒车灯控制命令
uint8  AlarmHornCtrlCmd      #  喇叭控制命令

