# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vehicle_msgs/EMS5.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EMS5(genpy.Message):
  _md5sum = "cd438c509bd33c2fdc3156e68bbb6b7a"
  _type = "vehicle_msgs/EMS5"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ID=0x0E0, Len=8, 20ms
uint8   BrakePedalSignal             # 制动踏板开关信号
uint8   AccPedalFaultFlag            # 加速踏板信号异常标志
uint8   RollingCountEMS5             # EMS5滚动计数值
float32 AccPedalPos                  # 加速踏板位置
uint8   CheckSumEMS5                 # EMS5校验值 
"""
  __slots__ = ['BrakePedalSignal','AccPedalFaultFlag','RollingCountEMS5','AccPedalPos','CheckSumEMS5']
  _slot_types = ['uint8','uint8','uint8','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       BrakePedalSignal,AccPedalFaultFlag,RollingCountEMS5,AccPedalPos,CheckSumEMS5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EMS5, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.BrakePedalSignal is None:
        self.BrakePedalSignal = 0
      if self.AccPedalFaultFlag is None:
        self.AccPedalFaultFlag = 0
      if self.RollingCountEMS5 is None:
        self.RollingCountEMS5 = 0
      if self.AccPedalPos is None:
        self.AccPedalPos = 0.
      if self.CheckSumEMS5 is None:
        self.CheckSumEMS5 = 0
    else:
      self.BrakePedalSignal = 0
      self.AccPedalFaultFlag = 0
      self.RollingCountEMS5 = 0
      self.AccPedalPos = 0.
      self.CheckSumEMS5 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3BfB().pack(_x.BrakePedalSignal, _x.AccPedalFaultFlag, _x.RollingCountEMS5, _x.AccPedalPos, _x.CheckSumEMS5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.BrakePedalSignal, _x.AccPedalFaultFlag, _x.RollingCountEMS5, _x.AccPedalPos, _x.CheckSumEMS5,) = _get_struct_3BfB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3BfB().pack(_x.BrakePedalSignal, _x.AccPedalFaultFlag, _x.RollingCountEMS5, _x.AccPedalPos, _x.CheckSumEMS5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.BrakePedalSignal, _x.AccPedalFaultFlag, _x.RollingCountEMS5, _x.AccPedalPos, _x.CheckSumEMS5,) = _get_struct_3BfB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3BfB = None
def _get_struct_3BfB():
    global _struct_3BfB
    if _struct_3BfB is None:
        _struct_3BfB = struct.Struct("<3BfB")
    return _struct_3BfB
