(cl:in-package vehicle_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          DR_X-VAL
          DR_X
          DR_Y-VAL
          DR_Y
          DR_Z-VAL
          DR_Z
          DR_HEADING-VAL
          DR_HEADING
          DR_ROLL-VAL
          DR_ROLL
          DR_PITCH-VAL
          DR_PITCH
          LF_SPEED-VAL
          LF_SPEED
          RF_SPEED-VAL
          RF_SPEED
          LR_SPEED-VAL
          LR_SPEED
          RR_SPEED-VAL
          RR_SPEED
          ROT_X-VAL
          ROT_X
          ROT_Y-VAL
          ROT_Y
          ROT_Z-VAL
          ROT_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          STEER-VAL
          STEER
          BRAKE-VAL
          BRAKE
          FUEL-VAL
          FUEL
          TRANS-VAL
          TRANS
          VEHICLESTATE-VAL
          VEHICLESTATE
          MODE-VAL
          MODE
          DRSTATUS-VAL
          DRSTATUS
          ERRORSTATUS-VAL
          ERRORSTATUS
          EMERGENCY_FLAG-VAL
          EMERGENCY_FLAG
          HARDSWITCH_ON-VAL
          HARDSWITCH_ON
))