(cl:in-package vehicle_msgs-msg)
(cl:export '(ELECTRICACCPEDAL-VAL
          ELECTRICACCPEDAL
          ANGLEWHEEL-VAL
          ANGLEWHEEL
          BRAKEREQ-VAL
          BRAKEREQ
          ANGLULARACCLERATION-VAL
          ANGLULARACCLERATION
          AUTODRIVEENABLE-VAL
          AUTODRIVEENABLE
          EPBPARKINGREQ-VAL
          EPBPARKINGREQ
          ROLLINGCOUNTHAD1-VAL
          ROLLINGCOUNTHAD1
          CHECKSUMHAD1-VAL
          CHECKSUMHAD1
))