(cl:in-package vehicle_msgs-msg)
(cl:export '(GPS_FLAG-VAL
          GPS_FLAG
          GPS_WEEK-VAL
          GPS_WEEK
          GPS_MILLISECOND-VAL
          GPS_MILLISECOND
          LLHPOS-VAL
          LLHPOS
          GAUSSPOS-VAL
          GAUSSPOS
          HEIGHT-VAL
          HEIGHT
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          AZIMUTH-VAL
          AZIMUTH
          NORTHVELOCITY-VAL
          NORTHVELOCITY
          EASTVELOCITY-VAL
          EASTVELOCITY
          UPVELOCITY-VAL
          UPVELOCITY
          POSITIONSTATUS-VAL
          POSITIONSTATUS
          MOTION_FLAG-VAL
          MOTION_FLAG
          MOTION_WEEK-VAL
          MOTION_WEEK
          MOTION_MILLISECOND-VAL
          MOTION_MILLISECOND
          DRPOS-VAL
          DRPOS
          DRHEIGHT-VAL
          DRHEIGHT
          DRAZIMUTH-VAL
          DRAZIMUTH
          DRNORTHVELOCITY-VAL
          DRNORTHVELOCITY
          DREASTVELOCITY-VAL
          DREASTVELOCITY
          DRUPVELOCITY-VAL
          DRUPVELOCITY
          RESERVED-VAL
          RESERVED
))