(cl:in-package vehicle_msgs-msg)
(cl:export '(FLWHEELPULSECOUNTER-VAL
          FLWHEELPULSECOUNTER
          FRWHEELPULSECOUNTER-VAL
          FRWHEELPULSECOUNTER
          RLWHEELPULSECOUNTER-VAL
          RLWHEELPULSECOUNTER
          RRWHEELPULSECOUNTER-VAL
          RRWHEELPULSECOUNTER
          FLWHEELPULSECOUNTERVALIDITY-VAL
          FLWHEELPULSECOUNTERVALIDITY
          FRWHEELPULSECOUNTERVALIDITY-VAL
          FRWHEELPULSECOUNTERVALIDITY
          LONGITUDINALACCELERATION-VAL
          LONGITUDINALACCELERATION
          RLWHEELPULSECOUNTERVALIDITY-VAL
          RLWHEELPULSECOUNTERVALIDITY
          RRWHEELPULSECOUNTERVALIDITY-VAL
          RRWHEELPULSECOUNTERVALIDITY
          LONGITUDINALACCELERATIONFLAG-VAL
          LONGITUDINALACCELERATIONFLAG
))