(cl:in-package vehicle_msgs-msg)
(cl:export '(LEFTLIGHTSTATE-VAL
          LEFTLIGHTSTATE
          RIGHTLIGHTSTATE-VAL
          RIGHTLIGHTSTATE
          POSITIONLAMPSTATE-VAL
          POSITIONLAMPSTATE
          HIGHBEAMSTATE-VAL
          HIGHBEAMSTATE
          LOWBEAMSTATE-VAL
          LOWBEAMSTATE
          BACKFOGLIGHTSTATE-VAL
          BACKFOGLIGHTSTATE
          FRONTFOGLIGHTSTATE-VAL
          FRONTFOGLIGHTSTATE
))