(cl:in-package vehicle_msgs-msg)
(cl:export '(FRONTWIPERCTRLCMD-VAL
          FRONTWIPERCTRLCMD
          REARWIPERCTRLCMD-VAL
          REARWIPERCTRLCMD
          LOWBEAMCTRLCMD-VAL
          LOWBEAMCTRLCMD
          HIGHBEAMCTRLCMD-VAL
          HIGHBEAMCTRLCMD
          BACKFOGLIGHTCTRLCMD-VAL
          BACKFOGLIGHTCTRLCMD
          FRONTFOGLIGHTCTRLCMD-VAL
          FRONTFOGLIGHTCTRLCMD
          POSITIONLAMPCTRLCMD-VAL
          POSITIONLAMPCTRLCMD
          LEFTLIGHTCTRLCMD-VAL
          LEFTLIGHTCTRLCMD
          RIGHTLIGHTCTRLCMD-VAL
          RIGHTLIGHTCTRLCMD
          HARZADCTRLCMD-VAL
          HARZADCTRLCMD
          BRAKELAMPCTRLCMD-VAL
          BRAKELAMPCTRLCMD
          REVERSINGLAMPCTRLCMD-VAL
          REVERSINGLAMPCTRLCMD
          ALARMHORNCTRLCMD-VAL
          ALARMHORNCTRLCMD
))