(cl:in-package vehicle_msgs-msg)
(cl:export '(ROLLINGCOUNTEPS2-VAL
          ROLLINGCOUNTEPS2
          DRIVERSTEERINGINTERFERENCEDETECTED-VAL
          DRIVERSTEERINGINTERFERENCEDETECTED
          DRIVERSTEERINGINTERFERENCEDETECTEDVALIDITY-VAL
          DRIVERSTEERINGINTERFERENCEDETECTEDVALIDITY
          ELECTRICALPOWERSTEERINGAVAILABLITYSTATUS-VAL
          ELECTRICALPOWERSTEERINGAVAILABLITYSTATUS
          ELECTRICALPOWERSTEERINGAVAILABLITYSTATUSPROTECTIONVALUE-VAL
          ELECTRICALPOWERSTEERINGAVAILABLITYSTATUSPROTECTIONVALUE
          STEERINGTORQUEACT-VAL
          STEERINGTORQUEACT
))