(cl:in-package vehicle_msgs-msg)
(cl:export '(ACTUALFRONTWHEELANGLE-VAL
          ACTUALFRONTWHEELANGLE
          DESIREDFRONTWHEELANGLE-VAL
          DESIREDFRONTWHEELANGLE
          ACTUALCURVATURE-VAL
          ACTUALCURVATURE
          DESIREDCURVATURE-VAL
          DESIREDCURVATURE
          BCANCONTROLFLAG-VAL
          BCANCONTROLFLAG
          LEFTLIGHTFLAG-VAL
          LEFTLIGHTFLAG
          RIGHTLIGHTFLAG-VAL
          RIGHTLIGHTFLAG
))