(cl:in-package vehicle_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MESSAGEID-VAL
          MESSAGEID
          LOCALSTAMP-VAL
          LOCALSTAMP
          GLOBALSTAMP-VAL
          GLOBALSTAMP
          TARGETID-VAL
          TARGETID
          RANGE-VAL
          RANGE
          ANGLE-VAL
          ANGLE
          X-VAL
          X
          Y-VAL
          Y
          HEIGHT-VAL
          HEIGHT
          WIDTH-VAL
          WIDTH
          RANGERATE-VAL
          RANGERATE
          LATRATE-VAL
          LATRATE
          TRACKSTATUS-VAL
          TRACKSTATUS
          ISACCTARGET-VAL
          ISACCTARGET
          ISCMBBTARGET-VAL
          ISCMBBTARGET
          ISFCWTARGET-VAL
          ISFCWTARGET
))