(cl:in-package vehicle_msgs-msg)
(cl:export '(VEHSPDVALIDFLAG-VAL
          VEHSPDVALIDFLAG
          VACUUMORIGINALVALUEVALIDITY-VAL
          VACUUMORIGINALVALUEVALIDITY
          BRAKEOILPRESS-VAL
          BRAKEOILPRESS
          VEHICLESPEED-VAL
          VEHICLESPEED
          VACUUMORIGINALVALUE-VAL
          VACUUMORIGINALVALUE
))