(cl:in-package vehicle_msgs-msg)
(cl:export '(THROTTLEPOSFEEDBACK-VAL
          THROTTLEPOSFEEDBACK
          ENGSPD-VAL
          ENGSPD
          ACTUALACCPEDAL-VAL
          ACTUALACCPEDAL
          AUTODRIVESTATUS-VAL
          AUTODRIVESTATUS
          ENGSPDSIGNALERRFLAG-VAL
          ENGSPDSIGNALERRFLAG
          ACCPEDALINTERVENTENABLE-VAL
          ACCPEDALINTERVENTENABLE
          ROLLINGCOUNTEMS1-VAL
          ROLLINGCOUNTEMS1
          CHECKSUMEMS1-VAL
          CHECKSUMEMS1
))