// Generated by gencpp from file vehicle_msgs/BCM3.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_BCM3_H
#define VEHICLE_MSGS_MESSAGE_BCM3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_msgs
{
template <class ContainerAllocator>
struct BCM3_
{
  typedef BCM3_<ContainerAllocator> Type;

  BCM3_()
    : FrontWiperState(0)  {
    }
  BCM3_(const ContainerAllocator& _alloc)
    : FrontWiperState(0)  {
  (void)_alloc;
    }



   typedef uint8_t _FrontWiperState_type;
  _FrontWiperState_type FrontWiperState;




  typedef boost::shared_ptr< ::vehicle_msgs::BCM3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::BCM3_<ContainerAllocator> const> ConstPtr;

}; // struct BCM3_

typedef ::vehicle_msgs::BCM3_<std::allocator<void> > BCM3;

typedef boost::shared_ptr< ::vehicle_msgs::BCM3 > BCM3Ptr;
typedef boost::shared_ptr< ::vehicle_msgs::BCM3 const> BCM3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::BCM3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::BCM3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vehicle_msgs': ['/mnt/hgfs/Share/DFAx7i/ros_messages/src/vehicle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::BCM3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::BCM3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::BCM3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::BCM3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::BCM3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::BCM3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::BCM3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c189000e93ecf02e8d6beed036bb8970";
  }

  static const char* value(const ::vehicle_msgs::BCM3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc189000e93ecf02eULL;
  static const uint64_t static_value2 = 0x8d6beed036bb8970ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::BCM3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/BCM3";
  }

  static const char* value(const ::vehicle_msgs::BCM3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::BCM3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ID=0x33C, Len=3, 100ms                        \n\
uint8  FrontWiperState              # 前雨刮开光状态\n\
";
  }

  static const char* value(const ::vehicle_msgs::BCM3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::BCM3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FrontWiperState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BCM3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::BCM3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::BCM3_<ContainerAllocator>& v)
  {
    s << indent << "FrontWiperState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FrontWiperState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_BCM3_H
