// Generated by gencpp from file vehicle_msgs/MAINSW.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_MAINSW_H
#define VEHICLE_MSGS_MESSAGE_MAINSW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_msgs
{
template <class ContainerAllocator>
struct MAINSW_
{
  typedef MAINSW_<ContainerAllocator> Type;

  MAINSW_()
    : MainSwithStatus(0)  {
    }
  MAINSW_(const ContainerAllocator& _alloc)
    : MainSwithStatus(0)  {
  (void)_alloc;
    }



   typedef uint8_t _MainSwithStatus_type;
  _MainSwithStatus_type MainSwithStatus;




  typedef boost::shared_ptr< ::vehicle_msgs::MAINSW_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::MAINSW_<ContainerAllocator> const> ConstPtr;

}; // struct MAINSW_

typedef ::vehicle_msgs::MAINSW_<std::allocator<void> > MAINSW;

typedef boost::shared_ptr< ::vehicle_msgs::MAINSW > MAINSWPtr;
typedef boost::shared_ptr< ::vehicle_msgs::MAINSW const> MAINSWConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::MAINSW_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::MAINSW_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vehicle_msgs': ['/mnt/hgfs/Share/DFAx7i/ros_messages/src/vehicle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::MAINSW_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::MAINSW_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::MAINSW_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
{
  static const char* value()
  {
    return "132e4b97ab6f48f4a26bdfbc6a7ca6a7";
  }

  static const char* value(const ::vehicle_msgs::MAINSW_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x132e4b97ab6f48f4ULL;
  static const uint64_t static_value2 = 0xa26bdfbc6a7ca6a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/MAINSW";
  }

  static const char* value(const ::vehicle_msgs::MAINSW_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8  MainSwithStatus     #  主控制开关状态，1-开关有效，0-开关无效\n\
";
  }

  static const char* value(const ::vehicle_msgs::MAINSW_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MainSwithStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MAINSW_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::MAINSW_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::MAINSW_<ContainerAllocator>& v)
  {
    s << indent << "MainSwithStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.MainSwithStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_MAINSW_H
